import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import * as Clipboard from "expo-clipboard";
import { LinearGradient } from "expo-linear-gradient";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import {
  Alert,
  Pressable,
  ScrollView,
  Share,
  StatusBar,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

type OutputType = "email" | "file" | "escalation";

type Params = {
  text?: string;
  type?: string;
  outputType?: OutputType;
};

const defaultLabels: Record<string, string> = {
  email: "Email Response",
  file: "File Note",
  escalation: "Escalation Response",
};

export default function ResponseScreen() {
  const params = useLocalSearchParams<Params>();
  const insets = useSafeAreaInsets();
  const [copying, setCopying] = useState(false);

  const responseText = useMemo(() => {
    if (!params.text) return "No response available.";
    if (typeof params.text === "object") {
      return JSON.stringify(params.text, null, 2);
    }
    return params.text;
  }, [params.text]);

  const responseTypeLabel = params.type || defaultLabels[params.outputType || "email"] || "Generated Output";

  function onBack() {
    if (router.canGoBack()) {
      router.back();
    } else {
      router.replace("/(tabs)");
    }
  }

  const onShare = async () => {
    try {
      await Share.share({
        message: responseText,
        title: responseTypeLabel,
      });
    } catch (error) {
      console.log("Share error:", error);
    }
  };

  async function onCopy() {
    try {
      setCopying(true);
      await Clipboard.setStringAsync(responseText);
      Alert.alert("Success", "Draft copied to clipboard.");
    } catch {
      Alert.alert("Error", "Failed to copy text.");
    } finally {
      setTimeout(() => setCopying(false), 2000);
    }
  }

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" />
      
      {/* Dynamic Header */}
      <LinearGradient
        colors={["#276bbd", "#0B3C7A"]}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 0 }}
        style={[styles.header, { paddingTop: insets.top }]}
      >
        <View style={styles.headerContent}>
          <Pressable onPress={onBack} style={styles.iconButton}>
            <Ionicons name="chevron-back" size={28} color="#FFFFFF" />
          </Pressable>
          <Text style={styles.headerTitle}>Review Draft</Text>
          <Pressable onPress={onShare} style={styles.iconButton}>
            <Ionicons name="share-outline" size={24} color="#FFFFFF" />
          </Pressable>
        </View>
      </LinearGradient>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.scrollContent, { paddingBottom: insets.bottom + 100 }]}
        showsVerticalScrollIndicator={false}
      >
        {/* Meta Section */}
        <View style={styles.metaRow}>
          <View style={styles.typeBadge}>
            <MaterialCommunityIcons name="robot" size={16} color="#1469C9" />
            <Text style={styles.typeText}>{responseTypeLabel}</Text>
          </View>
          <Text style={styles.timestamp}>{new Date().toLocaleDateString()}</Text>
        </View>

        {/* The Document Card */}
        <View style={styles.documentCard}>
          <View style={styles.cardHeader}>
            <Text style={styles.cardHeaderLabel}>AI GENERATED CONTENT</Text>
            <View style={styles.cardHeaderLine} />
          </View>
          
          <Text style={styles.bodyText}>{responseText}</Text>
          
          <View style={styles.cardFooter}>
            <Text style={styles.footerNote}>This draft was generated by AI and should be reviewed for accuracy.</Text>
          </View>
        </View>
      </ScrollView>

      {/* Primary Action Button */}
      <View style={[styles.floatingFooter, { paddingBottom: insets.bottom + 16 }]}>
        <Pressable 
          onPress={onCopy} 
          disabled={copying}
          style={({ pressed }) => [
            styles.primaryButton,
            pressed && { scale: 0.98, opacity: 0.9 }
          ]}
        >
          <LinearGradient
            colors={copying ? ["#10B981", "#059669"] : ["#276bbd", "#0B3C7A"]}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 0 }}
            style={styles.buttonGradient}
          >
            <Ionicons name={copying ? "checkmark-done" : "copy-outline"} size={20} color="#FFF" />
            <Text style={styles.buttonText}>
              {copying ? "Copied to Clipboard" : "Copy Draft"}
            </Text>
          </LinearGradient>
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    elevation: 8,
    shadowColor: "#0B3C7A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    height: 64,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  iconButton: {
    padding: 8,
    borderRadius: 12,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 4,
    marginBottom: 16,
  },
  typeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DBEAFE",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  typeText: {
    color: "#1E40AF",
    fontSize: 13,
    fontWeight: "700",
  },
  timestamp: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "600",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
  },
  documentCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
  },
  cardHeader: {
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  cardHeaderLabel: {
    fontSize: 10,
    color: "#94A3B8",
    fontWeight: "800",
    letterSpacing: 1,
  },
  cardHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#F1F5F9",
  },
  bodyText: {
    color: "#334155",
    fontSize: 16,
    lineHeight: 28,
    letterSpacing: 0.2,
  },
  cardFooter: {
    marginTop: 30,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  footerNote: {
    fontSize: 12,
    color: "#94A3B8",
    fontStyle: "italic",
    textAlign: "center",
    lineHeight: 18,
  },
  floatingFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(248, 250, 252, 0.95)",
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  primaryButton: {
    borderRadius: 16,
    overflow: "hidden",
    elevation: 4,
    shadowColor: "#276bbd",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  buttonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 60,
    gap: 12,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
  },
});