import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "#F8FAFC" },
  headerGradient: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  safeHeader: { paddingHorizontal: 18, paddingBottom: 10 },
  navBar: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  loaderScreen: { flex: 1 },
  loaderGradient: { flex: 1, justifyContent: "center", alignItems: "center" },
  loaderContent: { alignItems: "center", paddingHorizontal: 30 },
  loaderIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  loaderTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
    textAlign: "center",
  },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  clearButton: {
    position: "absolute",
    top: 10,
    right: 10,

    width: 28,
    height: 28,
    borderRadius: 14,

    backgroundColor: "rgba(255,255,255,0.9)",

    alignItems: "center",
    justifyContent: "center",

    // subtle shadow
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  clearTextButton: {
    position: "absolute",
    top: 0,
    right: 0,

    paddingHorizontal: 10,
    paddingVertical: 4,

    borderRadius: 8,
    backgroundColor: "rgba(15, 76, 156, 0.08)",

    borderWidth: 1,
    borderColor: "rgba(15, 76, 156, 0.2)",
  },
  clearText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#0F4C9C",
  },
  navTitle: { fontSize: 19, fontWeight: "800", color: "#FFFFFF" },
  creditBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.14)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#22C55E",
  },
  creditValue: { color: "#ecf843", fontSize: 13, fontWeight: "800" },

  sectionLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 6,
    marginTop: 6,
  },
  workspaceItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF",
    paddingHorizontal: 20,
    // paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    height: 40,
    gap: 8,
  },
  workspaceItemActive: { backgroundColor: "#0F4C9C", borderColor: "#0f4c9c" },
  workspaceTile: {
    width: 140,
    height: 40,
    // marginBottom: 12,
  },
  workspaceText: { fontSize: 14, fontWeight: "700", color: "#64748B" },
  workspaceGrid: {
    flexDirection: "row",
    gap: 8,
  },
  workspaceTextActive: { color: "#FFF" },
  addWorkspaceBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EEF2FF",
    paddingHorizontal: 8,
    borderRadius: 16,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "#0F4C9C",
    gap: 4,
  },
  addWorkspaceText: { fontSize: 14, fontWeight: "800", color: "#0F4C9C" },
  tabContainer: { paddingVertical: 10, paddingHorizontal: 4, gap: 10 },
  tabItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
  },
  tabItemActive: { backgroundColor: "#1F2937", elevation: 3 },
  tabText: { fontSize: 14, color: "#374151", fontWeight: "500" },
  tabTextActive: { color: "#FFFFFF", fontWeight: "600" },
  glassCard: {
    backgroundColor: "#FFFFFF",
    marginTop: 20,
    borderRadius: 20,
    padding: 12, // reduced from 16

    elevation: 8,
    shadowColor: "#0F4C9C",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },

    borderWidth: 1,
    borderColor: "rgba(15, 76, 156, 0.15)",
  },
  // fieldGroup: { marginVertical: 1 },
  fieldHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    // marginBottom: 12,
  },
  iconCircle: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  inputLabel: { fontSize: 14, fontWeight: "700", color: "#1E293B" },
  inputWrapper: {
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    position: "relative",

    height: 180,
    overflow: "hidden",

    paddingRight: 8,
  },
  mainTextInput: {
    fontSize: 16,
    color: "#334155",
    height: 170,
    textAlignVertical: "top",

    paddingHorizontal: 12, // reduced
    paddingTop: 8, // ADD (tight top)
    paddingBottom: 8, // ADD (tight bottom)
    paddingRight: 12,
  },
  inputActions: {
    position: "absolute",
    right: 10,
    bottom: 0,

    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  //   width: 36,
  //   height: 36,
  //   borderRadius: 10,
  //   backgroundColor: "#F1F5F9",

  //   alignItems: "center",
  //   justifyContent: "center",

  //   borderWidth: 1,
  //   borderColor: "#E2E8F0",
  // },
  recordButton: {
    backgroundColor: "#0F4C9C",
    borderColor: "#0F4C9C",
  },
  recordingActive: {
    backgroundColor: "#DC2626",
    borderColor: "#DC2626",
  },
  recordingText: {
    marginTop: 12,
    color: "#0F4C9C",
    fontSize: 13,
    fontWeight: "700",
  },
  imagePreviewContainer: {
    position: "absolute",
    right: 80,
    bottom: 0,
    width: 60,
    height: 60,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
  },
  imagePreview: {
    width: "100%",
    height: "100%",
  },
  removeImageButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  scenarioScrollButton: {
    position: "absolute",
    right: 8,
    bottom: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#EFF6FF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  listeningText: {
    // marginTop: 10,
    fontSize: 13,
    fontWeight: "700",
    color: "#0F4C9C",
  },
  generateBtn: { marginTop: 10, borderRadius: 20, overflow: "hidden" },
  gradientBtn: {
    height: 64,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  btnText: { color: "#FFFFFF", fontSize: 17, fontWeight: "800" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 20, fontWeight: "800", color: "#0F172A" },
  modalLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#94A3B8",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  modalInput: {
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    fontSize: 15,
    color: "#0F172A",
  },
  modalScrollContent: {
    gap: 12,
    paddingBottom: 40,
  },
  rowTwoColumn: {
    flexDirection: "row",
    gap: 10,
  },
  rowColumn: {
    flex: 1,
  },
  modalActionBtn: {
    backgroundColor: "#0F4C9C",
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: "center",
    marginTop: 10,
  },
  modalActionText: { color: "#FFF", fontSize: 16, fontWeight: "800" },
  dropdownTrigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFF",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    // marginBottom: 20,
  },
  dropdownLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  taskIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  dropdownValueText: { fontSize: 15, fontWeight: "700", color: "#1E293B" },
  taskOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 16,
    marginBottom: 8,
    gap: 12,
  },
  taskOptionActive: { backgroundColor: "#F1F5F9" },
  taskOptionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: "#64748B",
  },
  taskOptionTextActive: { color: "#0F4C9C", fontWeight: "800" },
  // micBtn: {
  //   // backgroundColor: "#0F4C9C",
  //   // borderColor: "#0F4C9C",
  // },
  micBtnActive: { transform: [{ scale: 1.1 }] },
  micBtnDisabled: { opacity: 0.5 },
  workspaceScroll: { paddingLeft: 4, gap: 10, marginBottom: 25 },
});